---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-disk-ssd
provisioner: disk.csi.azure.com
parameters:
  skuName: Premium_LRS  
  storageaccounttype: Premium_LRS  
  csi.storage.k8s.io/fstype: ext4  
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
