[cloud-provider]
azure-region = koreacentral
azure-acr-resource-group = rg-elbacr
azure-acr-name = elbacr
azure-resource-group = rg-elb-koc
azure-storage-account = stgelb
azure-storage-account-container = blast-db

# Taxonomy Strategy: pathogen subset DB (~25 GB)
# Virus (10239) + Plasmodium (5820) only
# No merge needed — standard query-split

[cluster]
name = elb-v2-taxonomy
machine-type = Standard_E32s_v3
num-nodes = 1
exp-use-local-ssd = true

[blast]
program = blastn
db = https://stgelb.blob.core.windows.net/blast-db/core_nt_pathogen/core_nt_pathogen
queries = https://stgelb.blob.core.windows.net/queries/pathogen-10.fa
results = https://stgelb.blob.core.windows.net/results/v2/taxonomy/s4-taxonomy-10q
options = -max_target_seqs 500 -evalue 0.05 -word_size 28 -dust yes -soft_masking true -outfmt 7
batch-len = 100000
mem-limit = 4G
