[cloud-provider]
azure-region = koreacentral
azure-acr-resource-group = rg-elbacr
azure-acr-name = elbacr
azure-resource-group = rg-elb-koc
azure-storage-account = stgelb
azure-storage-account-container = blast-db

# C2-subset-shard3: Pathogen subset + 3 shards on 3×E16s
# Combined Strategy

[cluster]
name = elb-v3-combined
machine-type = Standard_E16s_v3
num-nodes = 3
exp-use-local-ssd = true

[blast]
program = blastn
db = https://stgelb.blob.core.windows.net/blast-db/core_nt_pathogen/core_nt_pathogen
queries = https://stgelb.blob.core.windows.net/queries/pathogen-10.fa
results = https://stgelb.blob.core.windows.net/results/v3/combined/C2-subset-shard3
options = -max_target_seqs 500 -evalue 0.05 -word_size 28 -dust yes -soft_masking true -outfmt 7
batch-len = 100000
mem-limit = 4G
db-partitions = 3
db-partition-prefix = https://stgelb.blob.core.windows.net/blast-db/pathogen_3shards/core_nt_pathogen_shard_

[timeouts]
init-pv = 30
